### ISSUE TITLE
randomness backends

### ISSUE THREAD

**Issue by jjl** [dstebila/rlwekex#17]
Hi,

I see from the commit you made after merging my work that the /dev/urandom backend is quite slow.

I don't understand the overall structure of your code well enough yet to see how much of a saving can be made, but if we know how much randomness is required ahead of time, we can simply buffer it to avoid the syscall overhead which is presumably what is making performance suck (because the current functions don't return very much randomness at a time).

I'm also thinking about what other backends might be desirable. I've completely lost trust in the ability of openssl to get anything right, but there must be other options for secure userspace random generation. Any recommendations?

**Comment by dstebila** [comment]
Ultimately what we should do is simplify the randomness backend into a single backend that on initialization reads a 128-bit or 256-bit seed from /dev/urandom and then uses a standalone implementation of e.g. AES-CTR, or ChaCha20, or SHAKE to pseudorandomly expand on demand.  I'll see about putting together a design for this.

**Comment by jjl** [comment]
This sounds like a good idea (especially if you're running on FreeBSD, which won't return from a read to /dev/urandom until there is sufficient entropy to guarantee a good result). I'm not sure if you're suggesting avoiding depending on another library by just knocking together a quick implementation though. Given the importance of the SPRNG in maintaining crypto strength, I think it would be better to find a small library that is easily auditable and well-maintained and depend on that.

I'll look forward to seeing your design anyway.

**Comment by dstebila** [comment]
I've been working on a new project that will incorporate a variety of post-quantum key exchange protocols, including this ring-LWE protocol.  The new project has a simplified randomness back-end.  I'm not planning on maintaining this repository any more, instead directing my efforts to the new project.  It's at [https://github.com/open-quantum-safe/liboqs](https://github.com/open-quantum-safe/liboqs).

**Comment by jjl** [comment]
This is fantastic news. Being able to have these various PQ crypto projects in a properly embeddable library that can be used easily from real world apps is something I've been waiting for :)

**Comment by dstebila** [comment]
Glad to hear it.  Contributions and help welcome. :)
