### ISSUE TITLE
What is the exact entropy of the sample function ?

### ISSUE THREAD

**Issue by Boutoukoat** [dstebila/rlwekex#7]
Dead code elimination shows that more than 90% of the input randomness has no impact to the sample() algorithm. The reason comes from the 192 bit number comparison, where approx 96% of the decisions are taken when the first byte is compared, the remaining 23 bytes have no impact on the algorithm. The non-constant time version could be more than 20 times faster than the current version, if less entropy is fetched from the randomness source.

Equivalently, many bytes, bits and words of the entropy can be modified without having an impact on the output of the sample() function.

Regardless of the algorithmic speed, is the security level has high as expected ? The effective entropy of the sample function is only 2095 bytes. the effective entropy of rlwe_kex_generate_keypair() is about 4090 bytes.

**Comment by dstebila** [comment]
While it's true that most of the time a lot of the randomness isn't going to have an effect, our proof in the paper so far only holds assuming we do full sampling.  I'm aware of recent and upcoming research that suggests a way to do without this, but would have to see the details before deciding whether it's safe to make that change.
